name: rsv-analyzer-env

channels:
  - conda-forge
  - bioconda

dependencies:
  - python=3.10
  - pandas
  - mash=2.3
  - seqkit=2.13.0
  - nextclade=3.21.0
  - biopython=1.84
  - cd-hit=4.8.1
  - nextflow=25.10.4
  - openjdk=17
